myshop/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"profile/$", views.ProfilePage.as_view(), name="profile"),
]

myshop/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^shopbybrand/', include('shopbybrand.urls', namespace='shopbybrand')),
    url(r"^home/$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from . import views
app_name = 'shop'

urlpatterns = [
    url(r'^store/$', views.store, name='store'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),

]

myshop/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Indian Market</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/mycss.css'%}">
  </head>
  <body>

    <nav class="navbar navbar-fixed-top">
     <div class="container-fluid">
     <div style="height:50px;background: #a6e043; text-align: center; font-size: 20px; color:white">Guaranteed lowest price or your money back !</div>
      <!-- Brand and toggle get grouped for better mobile display -->
       <div class="navbar-header">
         <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="{% url 'accounts:profile' %}">IndiaMarket</a>
       </div>
       <div id="navbarCollapse" class="collapse navbar-collapse">
             {% if user.is_authenticated %}
                 <ul class="nav navbar-nav">
                  <li><a href="{% url 'shop:product_list' %}">Shop</a></li>
                  <li><a href="{% url 'shop:store' %}">Stores</a></li>
                 </ul>
                 <ul class="nav navbar-nav  navbar-right">
                    <li class="navbar-link" style="color:green; font-size: 20px;padding-top: 30px; ">
                         <span class="glyphicon glyphicon-user"></span> {{ user.username }}
                    </li>
                    <li><a class="navbar-link" href="{% url 'accounts:logout' %}">
                      Logout</a>
                    </li>
                    <li> <a class="navbar-link" href="{% url 'cart:cart_detail' %}">
                     <span class="glyphicon glyphicon-shopping-cart"></span>Cart</a>
                    </li>
                 </ul>
             {% else %}
                 <ul class="nav navbar-nav">
                     <li><a href="#">News</a></li>
                     <li><a href="#">Top Stores</a></li>
                     <li><a href="#">Offers</a></li>
                     <li><a href="#">Upcoming Deal</a></li>
                 </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li><a class="navbar-link" href="{% url 'accounts:login' %}">
                     <span class="glyphicon glyphicon-log-in"></span>  Login</a> </li>
                    <li><a class="navbar-link" href="{% url 'accounts:signup' %}">
                     <span class="glyphicon glyphicon-user"></span>Signup</a>
                    </li>
                  </ul>
            {% endif %}
       </div>
     </div>
    <hr>
 </nav>




          {% block content %}

          {% endblock %}


<footer id="myFooter">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 myCols">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 myCols">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 myCols">
                    <h5>Legal</h5>
                    <br>
                    <ul>
                        <li><a href="#">Terms of Service</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        </div>
    <hr style="width: 80%; color: black;">
        <div class="social-networks">
            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="facebook"><i class="fa fa-facebook-official"></i></a>
            <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
        </div>
        <div class="footer-copyright">
            <p>© 2017 Copyright Text </p>
        </div>
    </footer>




  </body>
</html>

myshop/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <br/><br/><br/><br/><br/><br/><br/><br/>
    <div class="container-fluid" style="height: 640px">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active" ></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
        <li data-target="#myCarousel" data-slide-to="5"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
                <img src="https://www.bigbasket.com/media/uploads/banner_images/Bangalore-1600-X-460-17Oct17.jpg" style="height: 640px" href="">
                 <div class="carousel-caption">
                    <h3>Los Angeles</h3>
                     <p>LA is always so much fun!</p>
                </div>
        </div>
        {% for c in categories %}
            <div class="item ">
             {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a  href="{{ c.get_absolute_url }}">
                    <img src="{{ c.image.url }}" style="height: 640px">
                </a>
                 <div class="carousel-caption">
                    <h3>Los Angeles</h3>
                     <p>LA is always so much fun!</p>
                </div>
             </div>
        {% endfor %}
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
    <br/><br/>
    <div style="background: rebeccapurple" class="container-fluid">
        <h3>Categories</h3>
        <ul class="cat_list">
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
        </ul>
       </div>
    <h1>Welcome to Star Social!</h1>
    <h2>The best community for all things on outer space!</h2>
    <h2>Login or Sign-up for free to get started!</h2>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}